name: Build kernel

on:
  workflow_call:
    inputs:
      kernelsu_variant:
        description: 'Variant of KernelSU'
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      CCACHE_DIR: ${{github.workspace}}/ccache
      CONFIG: sun
      FW_VERSION: BYI3
      DEBIAN_FRONTEND: noninteractive

    steps:
      - name: Configure KernelSU variant
        run: |
          if [ "${{ inputs.kernelsu_variant }}" == "SukiSU Ultra" ]; then
            echo "KSU_VARIANT=sukisu" >> "$GITHUB_ENV"
          elif [ "${{ inputs.kernelsu_variant }}" == "KernelSU Next" ]; then
            echo "KSU_VARIANT=next" >> "$GITHUB_ENV"
          else
            echo "Unknown KernelSU variant!"
            exit 1
          fi

      - name: Maximize build space
        run: |
          df -h

          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/local/.ghcup /opt/hostedtoolcache/CodeQL /usr/local/share/powershell /usr/share/swift
          sudo docker image prune --all --force
          echo "some directories deleted"

          # Regex-based purges (for bulk families like mysql, php, dotnet)
          sudo apt-get purge -y $(dpkg-query -W -f='${binary:Package}\n' | grep -E '^mysql|^php|^dotnet|^apache2|^snapd')

          # Remove large unwanted packages
          sudo apt-get purge --ignore-missing -y --allow-remove-essential \
            aria2 ansible azure-cli shellcheck rpm xorriso zsync \
            firefox gfortran-9 google-chrome-stable imagemagick \
            libmagickcore-dev libmagickwand-dev libmagic-dev ant ant-optional kubectl \
            mercurial apt-transport-https mono-complete \
            unixodbc-dev yarn chrpath libssl-dev libxft-dev \
            libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev \
            snmp pollinate libpq-dev postgresql-client powershell ruby-full \
            sphinxsearch subversion microsoft-edge-stable snapd shim-signed

          # Clean up
          sudo apt-get autoremove -y
          sudo apt-get autoclean -y
          echo "some packages purged"

          df -h

      - name: Create and Enable 3G Swap
        run: |
          sudo swapoff -a
          sudo fallocate -l 3G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          free -h

      - name: Install ccache
        run: sudo apt update && sudo apt install -y ccache python3 git curl

      - name: Configuring ccache for faster builds
        run: |
          ccache --version
          ccache --max-size=2G
          ccache --set-config=compression=true

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.CONFIG }}

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install -yq --no-install-recommends \
            python3 python-is-python3 git curl libelf-dev \
            build-essential flex bison libssl-dev \
            libncurses-dev liblz4-tool zlib1g-dev \
            libxml2-utils rsync unzip

      - name: Restore ccache from cache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ env.CONFIG }}-${{ env.KSU_VARIANT }}

      - name: Restore toolchain from cache
        id: toolchain-cache
        uses: actions/cache@v4
        with:
          path: toolchain
          key: toolchain-${{ env.CONFIG }}

      - name: Download toolchain
        if: ${{ !steps.toolchain-cache.outputs.cache-hit }}
        run: |
          echo "Download and unpack toolchain..."
          curl -L "https://github.com/miuirussia/android_kernel_samsung_sm8750/releases/download/toolchain/toolchain.tar.gz.part_aa" > toolchain.part00
          curl -L "https://github.com/miuirussia/android_kernel_samsung_sm8750/releases/download/toolchain/toolchain.tar.gz.part_ab" > toolchain.part01
          curl -L "https://github.com/miuirussia/android_kernel_samsung_sm8750/releases/download/toolchain/toolchain.tar.gz.part_ac" > toolchain.part02

          echo "Merging toolchain archive..."
          cat toolchain.part* > toolchain.tar.gz
          mkdir -p ./toolchain_temp
          tar -xzvf toolchain.tar.gz -C ./toolchain_temp/

          echo "Moving toolchain..."
          mkdir -p ./toolchain
          mv ./toolchain_temp/kernel_platform ./toolchain/
          rm toolchain.part* toolchain.tar.gz
          rm -rf ./toolchain_temp

      - name: Clone AnyKernel3 and Other Dependencies
        run: |
          echo "Cloning AnyKernel3 and other dependencies..."

          ANYKERNEL_BRANCH="gki-2.0"
          SUSFS_BRANCH="gki-android15-6.6"

          # Debug print the branches
          echo "Using branch for AnyKernel3: $ANYKERNEL_BRANCH"
          echo "Using branch for SUSFS: $SUSFS_BRANCH"

          # Clone repositories using the branch names
          git clone https://github.com/TheWildJames/AnyKernel3.git -b "$ANYKERNEL_BRANCH"
          git clone https://github.com/ShirkNeko/susfs4ksu.git -b "$SUSFS_BRANCH"
          git clone https://github.com/TheWildJames/kernel_patches.git
          git clone https://github.com/zzh20188/GKI_KernelSU_SUSFS.git zzh_kernel_patches

          # SukiSU patches
          git clone https://github.com/ShirkNeko/SukiSU_patch.git
          chmod +x $(pwd)/SukiSU_patch/kpm/patch_linux

      - name: Add KernelSU
        run: |
          cd "$CONFIG"

          if [ "${{ inputs.kernelsu_variant }}" == "SukiSU Ultra" ]; then
            echo "Adding SukiSU Ultra..."
            curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-test
          elif [ "${{ inputs.kernelsu_variant }}" == "KernelSU Next" ]; then
            echo "Adding KernelSU Next..."
            curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s next
          else
            echo "Unknown KernelSU variant!"
            exit 1
          fi

      - name: Apply SUSFS patch for ${{ inputs.kernelsu_variant }}
        run: |
          set -x

          echo "Change directory: $CONFIG..."
          cd "$CONFIG"

          echo "Applying SUSFS patches..."
          cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-android15-6.6.patch ./
          cp ../susfs4ksu/kernel_patches/fs/* ./fs/
          cp ../susfs4ksu/kernel_patches/include/linux/* ./include/linux/

          # Patch Samsung includes
          if ! grep -qxF '#include <trace/hooks/fs.h>' ./fs/namespace.c; then
            echo "Patch Samsung includes"
            sed -i '/#include <trace\/hooks\/blk.h>/a #include <trace\/hooks\/fs.h>' ./fs/namespace.c
          else
            echo "Line already present. Skipping insert."
          fi

          patch -p1 --fuzz=3 < 50_add_susfs_in_gki-android15-6.6.patch

          if [ "${{ inputs.kernelsu_variant }}" == "KernelSU Next" ]; then
            pushd ./KernelSU-Next

            cp ../../susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ./
            patch -p1 --forward < 10_enable_susfs_for_ksu.patch || true

            cp ../../kernel_patches/next/susfs_fix_patches/v1.5.9/fix_apk_sign.c.patch ./
            patch -p1 --forward < fix_apk_sign.c.patch

            cp ../../kernel_patches/next/susfs_fix_patches/v1.5.9/fix_core_hook.c.patch ./
            patch -p1 --forward --fuzz=3 < fix_core_hook.c.patch

            cp ../../kernel_patches/next/susfs_fix_patches/v1.5.9/fix_selinux.c.patch ./
            patch -p1 --forward < fix_selinux.c.patch

            cp ../../kernel_patches/next/susfs_fix_patches/v1.5.9/fix_ksud.c.patch ./
            patch -p1 --forward < fix_ksud.c.patch

            cp ../../kernel_patches/next/susfs_fix_patches/v1.5.9/fix_rules.c.patch ./
            patch -p1 --forward < fix_rules.c.patch

            cp ../../kernel_patches/next/susfs_fix_patches/v1.5.9/fix_sucompat.c.patch ./
            patch -p1 --forward < fix_sucompat.c.patch

            cp ../../kernel_patches/next/susfs_fix_patches/v1.5.9/fix_kernel_compat.c.patch ./
            patch -p1 --forward < fix_kernel_compat.c.patch

            popd
          fi


      - name: Apply syscall hook
        run: |
          echo "Change directory: $CONFIG..."
          cd "$CONFIG"
          if [ "${{ inputs.kernelsu_variant }}" == "SukiSU Ultra" ]; then
            echo "Applying hooks for SukiSU Ultra..."
            cp ../SukiSU_patch/hooks/syscall_hooks.patch ./
            patch -p1 --fuzz=3 < syscall_hooks.patch
          elif [ "${{ inputs.kernelsu_variant }}" == "KernelSU Next" ]; then
            echo "Applying hooks for KernelSU Next..."
            cp ../kernel_patches/next/scope_min_manual_hooks_v1.4.patch ./
            patch -p1 -F 3 < scope_min_manual_hooks_v1.4.patch
          else
            echo "Unknown KernelSU variant!"
            exit 1
          fi

      - name: Apply Hide Stuff Patches
        run: |
          echo "Changing to configuration directory: $CONFIG..."
          cd "$CONFIG"
          # Apply spoof patch
          if [ "${{ inputs.kernelsu_variant }}" == "SukiSU Ultra" ]; then
            cp ../SukiSU_patch/69_hide_stuff.patch ./
            patch -p1 --fuzz=3 < 69_hide_stuff.patch
          elif [ "${{ inputs.kernelsu_variant }}" == "KernelSU Next" ]; then
            cp ../kernel_patches/69_hide_stuff.patch ./
            patch -p1 --fuzz=3 < 69_hide_stuff.patch
          else
            echo "Unknown KernelSU variant!"
            exit 1
          fi

      - name: Add SUSFS Configuration Settings
        run: |
          echo "Changing to configuration directory: $CONFIG..."
          cd "$CONFIG"

          CONFIG_FILE=./arch/arm64/configs/"$CONFIG"_gki_defconfig

          echo "Adding configuration settings to $CONFIG_FILE..."

          # Add KSU configuration settings
          echo "CONFIG_KSU=y" >> "$CONFIG_FILE"

          if [ "${{ inputs.kernelsu_variant }}" == "SukiSU Ultra" ]; then
            echo "Add SukiSU configuration settings..."

            echo "CONFIG_KPM=y" >> "$CONFIG_FILE"

            # Add SukiSU manual hook
            echo "CONFIG_KSU_MANUAL_HOOK=y" >> "$CONFIG_FILE"
            echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> "$CONFIG_FILE"
          elif [ "${{ inputs.kernelsu_variant }}" == "KernelSU Next" ]; then
            echo "Add KernelSU Next configuration settings..."

            echo "CONFIG_KSU_KPROBES_HOOK=n" >> "$CONFIG_FILE"
            echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> "$CONFIG_FILE"
          else
            echo "Unknown KernelSU variant!"
            exit 1
          fi

          # Add tmpfs config setting
          echo "CONFIG_TMPFS_XATTR=y" >> "$CONFIG_FILE"
          echo "CONFIG_TMPFS_POSIX_ACL=y" >> "$CONFIG_FILE"

          # Add tethering config setting
          echo "CONFIG_IP_NF_TARGET_TTL=y" >> "$CONFIG_FILE"
          echo "CONFIG_IP6_NF_TARGET_HL=y" >> "$CONFIG_FILE"
          echo "CONFIG_IP6_NF_MATCH_HL=y" >> "$CONFIG_FILE"

          # Add bbr and fq config setting
          echo "CONFIG_TCP_CONG_ADVANCED=y" >> "$CONFIG_FILE"
          echo "CONFIG_TCP_CONG_BBR=y" >> "$CONFIG_FILE"
          #echo "CONFIG_DEFAULT_CUBIC=n" >> "$CONFIG_FILE"
          #echo "CONFIG_DEFAULT_BBR=y" >> "$CONFIG_FILE"
          #echo 'CONFIG_DEFAULT_TCP_CONG="bbr"' >> "$CONFIG_FILE"
          #echo "CONFIG_NET_SCH_DEFAULT=y" >> "$CONFIG_FILE"
          #echo "CONFIG_DEFAULT_FQ=y" >> "$CONFIG_FILE"
          #echo 'CONFIG_DEFAULT_NET_SCH="fq"' >> "$CONFIG_FILE"
          #echo "CONFIG_NET_SCH_HTB=n" >> "$CONFIG_FILE"
          echo "CONFIG_TCP_CONG_BIC=n" >> "$CONFIG_FILE"
          echo "CONFIG_TCP_CONG_WESTWOOD=n" >> "$CONFIG_FILE"
          echo "CONFIG_TCP_CONG_HTCP=n" >> "$CONFIG_FILE"

          # Add SUSFS configuration settings
          echo "CONFIG_KSU_SUSFS=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_SUS_PATH=n" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=n" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> "$CONFIG_FILE"

          # Add rcu config setting
          echo "CONFIG_RCU_TRACE=n" >> "$CONFIG_FILE"

          # Add personal config setting
          echo "CONFIG_IP_NF_TARGET_ECN=y" >> "$CONFIG_FILE"

      - name: Force ECN + Reduce overhead
        run: |
          cd "$CONFIG/net/ipv4"

          sed -i 's/net->ipv4.sysctl_tcp_ecn = 2;/net->ipv4.sysctl_tcp_ecn = 1;/' tcp_ipv4.c
          grep "sysctl_tcp_ecn" tcp_ipv4.c
          #sed -i '/\.procname[[:space:]]*=[[:space:]]*"tcp_ecn"/, /^[[:space:]]*\}/ s/SYSCTL_TWO/SYSCTL_ONE/' sysctl_net_ipv4.c
          grep -A6 '\.procname.*tcp_ecn' sysctl_net_ipv4.c
          sed -i 's/net->ipv4.sysctl_tcp_pacing_ss_ratio = 200;/net->ipv4.sysctl_tcp_pacing_ss_ratio = 150;/' tcp_ipv4.c
          sed -i 's/net->ipv4.sysctl_tcp_pacing_ca_ratio = 120;/net->ipv4.sysctl_tcp_pacing_ca_ratio = 110;/' tcp_ipv4.c
          grep "sysctl_tcp_pacing" tcp_ipv4.c
          ls -t | grep -E 'tcp_|sysctl_'

      - name: Fix WiFi and Bluetooth on Samsung 6.6 GKI devices
        run: |
          set -x

          echo "Change directory: $CONFIG..."
          cd "$CONFIG"

          echo "Adding Samsung KDP exported symbols to abi_gki_aarch64_galaxy"
          SYMBOL_LIST=./android/abi_gki_aarch64_galaxy
          echo "kdp_set_cred_non_rcu" >> $SYMBOL_LIST
          echo "kdp_usecount_dec_and_test" >> $SYMBOL_LIST
          echo "kdp_usecount_inc" >> $SYMBOL_LIST

          echo "Adding Samsung KDP exported symbols definition to abi_gki_aarch64.stg"
          cp ../kernel_patches/samsung/min_kdp/add-min_kdp-symbols.patch ./

          # Remove line, that not exists in original file
          sed -i '81d;84d;85d;86d' add-min_kdp-symbols.patch

          patch -p1 --no-backup-if-mismatch < add-min_kdp-symbols.patch
          echo "Successfully added Samsung KDP exported symbols definition to abi_gki_aarch64.stg"

          echo "Adding Samsung minimal KDP driver"
          cp ../kernel_patches/samsung/min_kdp/min_kdp.c ./drivers
          echo "obj-y += min_kdp.o" >> ./drivers/Makefile

      - name: Symbol magic
        run: |
          echo "Change directory: $CONFIG..."
          cd "$CONFIG"

          echo "Export all symbol from abi_gki_aarch64"
          KSU_ROOT=./KernelSU
          if [ "${{ inputs.kernelsu_variant }}" == "KernelSU Next" ]; then
            KSU_ROOT=./KernelSU-Next
          fi
          SYMBOL_LIST=./android/abi_gki_aarch64

          echo "Add KernelSU symbols"
          cat $KSU_ROOT/kernel/export_symbol.txt | awk '{sub("[ \t]+","");print "  "$0}' >> $SYMBOL_LIST

      - name: Update lz4 to 1.10.0
        run: |
          set -x

          echo "Changing to configuration directory: $CONFIG..."
          cd "$CONFIG"

          files=(
            "lib/lz4/lz4_compress.c"
            "lib/lz4/lz4_decompress.c"
            "lib/lz4/lz4defs.h"
            "lib/lz4/lz4hc_compress.c"
          )

          for file in "${files[@]}"; do
            if [ -e "$file" ]; then
              rm "$file"
              echo "$file removed"
            else
              echo "$file not found"
            fi
          done

          cp -r ../zzh_kernel_patches/zram/lz4/* ./lib/lz4/
          cp -r ../zzh_kernel_patches/zram/include/linux/* ./include/linux/
          cp -r ../zzh_kernel_patches/zram/6.6/lz4_1.10.0.patch .

          patch -p1 -F 3 --fuzz=5 < lz4_1.10.0.patch

          if [ -f "fs/f2fs/Makefile" ]; then
            if ! grep -qF "f2fs-\$(CONFIG_F2FS_IOSTAT) += iostat.o" "fs/f2fs/Makefile"; then
              echo "f2fs-\$(CONFIG_F2FS_IOSTAT) += iostat.o" >> "fs/f2fs/Makefile"
              echo "Added: f2fs-\$(CONFIG_F2FS_IOSTAT) += iostat.o"
            else
              echo "Already exists: f2fs-\$(CONFIG_F2FS_IOSTAT) += iostat.o"
            fi
          else
            echo "File not found: fs/f2fs/Makefile"
          fi

      - name: Generate kernel info
        run: |
          set -x

          echo "Changing to configuration directory: $CONFIG..."
          cd "$CONFIG"

          LOCALVERSION_BASE=-android15-kdevlab-${{ env.FW_VERSION }}
          version_string="${LOCALVERSION_BASE}-g$(git rev-parse --short HEAD)"
          echo "${version_string}" > ./localversion

          CURRENT_TIME=$(date -u +"%a %b %d %H:%M:%S UTC %Y")
          echo "KBUILD_BUILD_TIMESTAMP=${CURRENT_TIME}" >> "$GITHUB_ENV"
          echo "KBUILD_BUILD_VERSION=1" >> "$GITHUB_ENV"

          echo "Patching mkcompile_h with BUILD_TIME=$CURRENT_TIME"
          if grep -q 'UTS_VERSION=' "./scripts/mkcompile_h"; then
            perl -pi -e "s{UTS_VERSION=\"\\\$\\(.*?\\)\"}{UTS_VERSION=\"#1 SMP PREEMPT $CURRENT_TIME\"}" "./scripts/mkcompile_h"
          else
            perl -0777 -pi -e "s{cat <<EOF}{cat <<EOF\n#undef UTS_VERSION\n#define UTS_VERSION \"#1 SMP PREEMPT $CURRENT_TIME\" } unless /UTS_VERSION/" "./scripts/mkcompile_h"
          fi

      - name: Build kernel
        run: |
          set -x

          KERNELPATCH=$(pwd)/SukiSU_patch/kpm/patch_linux

          echo "Changing to configuration directory: $CONFIG..."
          cd "$CONFIG"

          echo "Building the kernel..."

          # Clear Cache
          sudo sh -c 'sync; echo 3 > /proc/sys/vm/drop_caches'

          # Remove protected exports
          if [ -e BUILD.bazel ]; then
            sed -i '/^[[:space:]]*"protected_exports_list"[[:space:]]*:[[:space:]]*"android\/abi_gki_protected_exports_aarch64",$/d' BUILD.bazel
          fi
          rm ./android/abi_gki_protected_exports_* || echo "No protected exports!"
          rm ./android/gki_*_protected_modules || echo "No protected exports!"

          MAIN_DEFCONFIG=sun_gki_defconfig
          TOOLCHAIN=$(realpath "../toolchain/kernel_platform/prebuilts")

          export PATH=$TOOLCHAIN/build-tools/linux-x86/bin:$PATH
          export PATH=$TOOLCHAIN/build-tools/path/linux-x86:$PATH
          export PATH=$TOOLCHAIN/clang/host/linux-x86/clang-r510928/bin:$PATH
          export PATH=$TOOLCHAIN/clang-tools/linux-x86/bin:$PATH
          export PATH=$TOOLCHAIN/kernel-build-tools/linux-x86/bin:$PATH

          LLD_COMPILER_RT="-fuse-ld=lld --rtlib=compiler-rt"
          sysroot_flags+="--sysroot=$TOOLCHAIN/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/sysroot "
          cflags+="-I$TOOLCHAIN/kernel-build-tools/linux-x86/include "
          ldflags+="-L $TOOLCHAIN/kernel-build-tools/linux-x86/lib64 "
          ldflags+=${LLD_COMPILER_RT}
          export LD_LIBRARY_PATH="$TOOLCHAIN/kernel-build-tools/linux-x86/lib64"
          export HOSTCFLAGS="$sysroot_flags $cflags"
          export HOSTLDFLAGS="$sysroot_flags $ldflags"

          MAKE_ARGS=(
            "O=out"
            "ARCH=arm64"
            "CC=/usr/bin/ccache clang" # Quotes around the entire assignment
            "LLVM=1"
            "LLVM_IAS=1"
          )

          echo "Generate defconfig '$MAIN_DEFCONFIG'..."
          make "${MAKE_ARGS[@]}" $MAIN_DEFCONFIG
          if [ $? -ne 0 ]; then
            echo "Failed to generate defconfig '$MAIN_DEFCONFIG'"
            exit 1
          fi

          echo "Disable security features..."
          ./scripts/config --file out/.config \
            -d UH -d RKP -d KDP -d SECURITY_DEFEX -d INTEGRITY -d FIVE \
            -d TRIM_UNUSED_KSYMS -d PROCA -d PROCA_GKI_10 -d PROCA_S_OS \
            -d PROCA_CERTIFICATES_XATTR -d PROCA_CERT_ENG -d PROCA_CERT_USER \
            -d GAF -d GAF_V6 -d FIVE_CERT_USER -d FIVE_DEFAULT_HASH

          echo "Enable ThinLTO"
          ./scripts/config --file out/.config -e LTO_CLANG_THIN -d LTO_CLANG_FULL

          make -j$(nproc) "${MAKE_ARGS[@]}"

          kernel_release=$(cat ./out/include/config/kernel.release)

          echo "Kernel release: $kernel_release"

          if [ "${{ inputs.kernelsu_variant }}" == "SukiSU Ultra" ]; then
            pushd ./out/arch/arm64/boot

            $KERNELPATCH
            rm -rf Image
            mv oImage Image

            popd
          fi

          mkdir -p ../dist
          cp ./out/arch/arm64/boot/Image ../dist/Image

          ccache -s

      - name: Compress patched kernel source
        run: |
          echo "Preparing kernel source: $CONFIG"
          cd "$GITHUB_WORKSPACE"
          tar -cf "./dist/source-$CONFIG-$FW_VERSION.tar.gz" \
          --use-compress-program=pigz \
          --exclude='.git' --exclude='out' \
          -C "$CONFIG" .

      - name: Create AnyKernel zip
        run: |
          cd ./AnyKernel3

          if [ "${{ inputs.kernelsu_variant }}" == "SukiSU Ultra" ]; then
            ZIP_NAME="S25-${{ env.FW_VERSION }}-SukiSU-Ultra-AnyKernel3.zip"
          elif [ "${{ inputs.kernelsu_variant }}" == "KernelSU Next" ]; then
            ZIP_NAME="S25-${{ env.FW_VERSION }}-KernelSU-Next-AnyKernel3.zip"
          else
            echo "Unknown KernelSU variant!"
            exit 1
          fi

          echo "Creating zip file: $ZIP_NAME..."
          cp ../dist/Image ./Image
          zip -r "../dist/$ZIP_NAME" ./*

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          compression-level: 0
          name: kernel-S25
          path: |
            ./dist/*AnyKernel3.zip
            ./dist/Image
            ./dist/source-*.tar.gz
