name: Build kernel and release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - name: Maximize Build Space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

      - name: Create and Enable 3G Swap
        run: |
          sudo swapoff -a
          sudo fallocate -l 3G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          free -h

      - name: Set CONFIG Environment Variable
        run: |
          CONFIG="sun"

          # Set CONFIG as an environment variable for future steps
          echo "CONFIG=$CONFIG" >> $GITHUB_ENV

          echo "CONFIG set to: $CONFIG"

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.CONFIG }}

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install -yq --no-install-recommends \
            python3 python-is-python3 git curl libelf-dev \
            build-essential flex bison libssl-dev \
            libncurses-dev liblz4-tool zlib1g-dev \
            libxml2-utils rsync unzip

      - name: Restore toolchain from cache
        uses: actions/cache@v4
        with:
          path: toolchain
          key: toolchain-${{ github.sha }}
          restore-keys: |
            toolchain-

      - name: Clone AnyKernel3 and Other Dependencies
        run: |
          echo "Cloning AnyKernel3 and other dependencies..."

          ANYKERNEL_BRANCH="gki-2.0"
          SUSFS_BRANCH="gki-android15-6.6"

          # Debug print the branches
          echo "Using branch for AnyKernel3: $ANYKERNEL_BRANCH"
          echo "Using branch for SUSFS: $SUSFS_BRANCH"

          # Clone repositories using the branch names
          git clone https://github.com/TheWildJames/AnyKernel3.git -b "$ANYKERNEL_BRANCH"
          git clone https://github.com/ShirkNeko/susfs4ksu.git -b "$SUSFS_BRANCH"
          git clone https://github.com/TheWildJames/kernel_patches.git

          # SukiSU patches
          git clone https://github.com/ShirkNeko/SukiSU_patch.git

          if [ ! -d toolchain ]; then
            echo "Download and unpack toolchain..."
            wget -O toolchain.part00 "https://github.com/YuzakiKokuban/android_kernel_samsung_sm8750/releases/download/toolchain/toolchainS25.tar.gz.00"
            wget -O toolchain.part01 "https://github.com/YuzakiKokuban/android_kernel_samsung_sm8750/releases/download/toolchain/toolchainS25.tar.gz.01"

            cat toolchain.part* > toolchain.tar.gz
            mkdir -p ./toolchain_temp
            tar -xzvf toolchain.tar.gz -C ./toolchain_temp/

            mkdir -p ./toolchain
            mv ./toolchain_temp/kernel_platform ./toolchain/
            rm toolchain.part* toolchain.tar.gz
            rm -rf ./toolchain_temp
          fi

          tree .

